import React, { useState, useRef } from 'react';
import { useReactToPrint } from 'react-to-print';
import jsPDF from 'jspdf';
import 'jspdf-autotable';

function PropertyReport({ property, onClose }) {
  const [reportFormat, setReportFormat] = useState('detailed');
  const [isGenerating, setIsGenerating] = useState(false);
  const reportRef = useRef(null);
  
  // Format currency values
  const formatCurrency = (value) => {
    return new Intl.NumberFormat('en-IN', {
      style: 'currency',
      currency: 'INR',
      maximumFractionDigits: 0
    }).format(value);
  };
  
  // Format date values
  const formatDate = (dateString) => {
    const options = { year: 'numeric', month: 'long', day: 'numeric' };
    return new Date(dateString).toLocaleDateString('en-IN', options);
  };
  
  // Handle printing the report
  const handlePrint = useReactToPrint({
    content: () => reportRef.current,
    documentTitle: `Property_Report_${property.id || 'Unknown'}`,
    onBeforeGetContent: () => {
      setIsGenerating(true);
      return new Promise((resolve) => {
        setTimeout(() => {
          setIsGenerating(false);
          resolve();
        }, 1000);
      });
    },
    onAfterPrint: () => setIsGenerating(false)
  });
  
  // Handle downloading PDF
  const handleDownloadPDF = () => {
    setIsGenerating(true);
    
    setTimeout(() => {
      const doc = new jsPDF();
      
      // Add header
      doc.setFontSize(20);
      doc.setTextColor(0, 31, 65);
      doc.text('ASSET-GURU Property Report', 105, 15, { align: 'center' });
      
      doc.setFontSize(12);
      doc.setTextColor(100, 100, 100);
      doc.text(`Generated on: ${new Date().toLocaleDateString('en-IN')}`, 105, 23, { align: 'center' });
      
      // Add property header
      doc.setFontSize(16);
      doc.setTextColor(0, 0, 0);
      doc.text(`${property.type || 'Property'}: ${property.address?.street || property.title || 'Property Report'}`, 14, 35);
      
      // Property details
      doc.setFontSize(14);
      doc.text('Property Details', 14, 45);
      
      const propertyDetails = [
        ['Property ID', property.id || 'N/A'],
        ['Type', property.type || 'N/A'],
        ['Location', `${property.address?.city || ''}, ${property.address?.state || ''}`],
        ['Owner', property.owner || 'N/A'],
        ['Area', property.propertyDetails?.area || 'N/A'],
        ['Market Value', formatCurrency(property.marketValue || property.propertyDetails?.price || 0)]
      ];
      
      doc.autoTable({
        startY: 50,
        head: [['Attribute', 'Value']],
        body: propertyDetails,
        theme: 'grid',
        headStyles: { fillColor: [0, 31, 65], textColor: [255, 255, 255] }
      });
      
      // Financial information
      doc.text('Financial Status', 14, doc.lastAutoTable.finalY + 15);
      
      const financialData = [
        ['Has Outstanding Loan', property.hasLoan ? 'Yes' : 'No'],
        ['Loan Amount', property.loanDetails?.originalAmount ? formatCurrency(property.loanDetails.originalAmount) : 'N/A'],
        ['Outstanding Amount', property.loanDetails?.outstandingAmount ? formatCurrency(property.loanDetails.outstandingAmount) : 'N/A'],
        ['Interest Rate', property.loanDetails?.interestRate ? `${property.loanDetails.interestRate}%` : 'N/A'],
        ['Lender', property.loanDetails?.lender || 'N/A'],
        ['Loan Start Date', property.loanDetails?.startDate ? formatDate(property.loanDetails.startDate) : 'N/A'],
        ['Loan End Date', property.loanDetails?.endDate ? formatDate(property.loanDetails.endDate) : 'N/A']
      ];
      
      doc.autoTable({
        startY: doc.lastAutoTable.finalY + 20,
        head: [['Financial Attribute', 'Value']],
        body: financialData,
        theme: 'grid',
        headStyles: { fillColor: [0, 31, 65], textColor: [255, 255, 255] }
      });
      
      // Verification information
      doc.text('Verification Status', 14, doc.lastAutoTable.finalY + 15);
      
      const verificationData = [
        ['DORIS Verified', 'Yes'],
        ['DLR Verified', 'Yes'],
        ['CERSAI Verified', 'Yes'],
        ['Last Verification Date', formatDate(new Date())]
      ];
      
      doc.autoTable({
        startY: doc.lastAutoTable.finalY + 20,
        head: [['Verification Source', 'Status']],
        body: verificationData,
        theme: 'grid',
        headStyles: { fillColor: [0, 31, 65], textColor: [255, 255, 255] }
      });
      
      // Add footer
      doc.setFontSize(10);
      doc.setTextColor(100, 100, 100);
      doc.text('This report is generated by ASSET-GURU for informational purposes only.', 105, 280, { align: 'center' });
      doc.text('© ASSET-GURU. All rights reserved.', 105, 285, { align: 'center' });
      
      // Save PDF
      doc.save(`Property_Report_${property.id || 'Unknown'}.pdf`);
      setIsGenerating(false);
    }, 1000);
  };
  
  // Handle downloading Excel/CSV
  const handleDownloadCSV = () => {
    setIsGenerating(true);
    
    setTimeout(() => {
      // Create CSV content
      const headers = [
        'Property ID',
        'Type',
        'Location',
        'Owner',
        'Area',
        'Market Value',
        'Has Loan',
        'Loan Amount',
        'Outstanding Amount',
        'Interest Rate',
        'Lender',
        'Loan Start Date',
        'Loan End Date',
        'DORIS Verified',
        'DLR Verified',
        'CERSAI Verified'
      ];
      
      const data = [
        property.id || '',
        property.type || '',
        `${property.address?.city || ''}, ${property.address?.state || ''}`,
        property.owner || '',
        property.propertyDetails?.area || '',
        (property.marketValue || property.propertyDetails?.price || 0).toString(),
        property.hasLoan ? 'Yes' : 'No',
        (property.loanDetails?.originalAmount || '').toString(),
        (property.loanDetails?.outstandingAmount || '').toString(),
        property.loanDetails?.interestRate || '',
        property.loanDetails?.lender || '',
        property.loanDetails?.startDate || '',
        property.loanDetails?.endDate || '',
        'Yes',
        'Yes',
        'Yes'
      ];
      
      const csvContent = [
        headers.join(','),
        data.join(',')
      ].join('\n');
      
      // Create download link
      const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.setAttribute('href', url);
      link.setAttribute('download', `Property_Report_${property.id || 'Unknown'}.csv`);
      link.style.visibility = 'hidden';
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      
      setIsGenerating(false);
    }, 1000);
  };
  
  return (
    <div className="property-report">
      <div className="report-controls mb-4">
        <div className="d-flex justify-content-between align-items-center">
          <h5 className="mb-0">
            <i className="bi bi-file-earmark-text me-2"></i>
            Property Report
          </h5>
          <button className="btn btn-sm btn-outline-secondary" onClick={onClose}>
            <i className="bi bi-x-lg"></i>
          </button>
        </div>
        
        <div className="report-actions mt-3">
          <div className="row g-2 align-items-center">
            <div className="col-md-6">
              <label className="form-label mb-1">Report Type</label>
              <select 
                className="form-select form-select-sm"
                value={reportFormat}
                onChange={(e) => setReportFormat(e.target.value)}
              >
                <option value="detailed">Detailed Report</option>
                <option value="financial">Financial Summary</option>
                <option value="verification">Verification Report</option>
              </select>
            </div>
            <div className="col-md-6">
              <label className="form-label mb-1">Download/Print Options</label>
              <div className="d-flex gap-2">
                <button 
                  className="btn btn-sm btn-primary flex-grow-1"
                  onClick={handlePrint}
                  disabled={isGenerating}
                >
                  <i className="bi bi-printer me-1"></i>
                  Print
                </button>
                <button 
                  className="btn btn-sm btn-success flex-grow-1"
                  onClick={handleDownloadPDF}
                  disabled={isGenerating}
                >
                  <i className="bi bi-file-earmark-pdf me-1"></i>
                  PDF
                </button>
                <button 
                  className="btn btn-sm btn-info text-white flex-grow-1"
                  onClick={handleDownloadCSV}
                  disabled={isGenerating}
                >
                  <i className="bi bi-file-earmark-excel me-1"></i>
                  CSV
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
      
      {isGenerating && (
        <div className="text-center py-5">
          <div className="spinner-border text-primary" role="status">
            <span className="visually-hidden">Generating report...</span>
          </div>
          <p className="mt-2">Generating your report...</p>
        </div>
      )}
      
      {!isGenerating && (
        <div 
          className="report-preview p-4 border rounded bg-white"
          ref={reportRef}
        >
          <div className="report-header text-center mb-4">
            <h4 className="mb-1">ASSET-GURU Property Report</h4>
            <p className="text-muted small mb-0">Generated on: {new Date().toLocaleDateString('en-IN')}</p>
          </div>
          
          <div className="property-header mb-4">
            <h5 className="border-bottom pb-2">{property.type || 'Property'}: {property.address?.street || property.title || 'Property Report'}</h5>
            <div className="row">
              <div className="col-md-6">
                <p className="mb-1"><strong>Property ID:</strong> {property.id || 'N/A'}</p>
                <p className="mb-1"><strong>Location:</strong> {property.address?.city || ''}, {property.address?.state || ''}</p>
                <p className="mb-1"><strong>Owner:</strong> {property.owner || 'N/A'}</p>
              </div>
              <div className="col-md-6">
                <p className="mb-1"><strong>Area:</strong> {property.propertyDetails?.area || 'N/A'}</p>
                <p className="mb-1"><strong>Type:</strong> {property.type || 'N/A'}</p>
                <p className="mb-1"><strong>Market Value:</strong> {formatCurrency(property.marketValue || property.propertyDetails?.price || 0)}</p>
              </div>
            </div>
          </div>
          
          {(reportFormat === 'detailed' || reportFormat === 'financial') && (
            <div className="financial-section mb-4">
              <h5 className="border-bottom pb-2">Financial Status</h5>
              <div className="table-responsive">
                <table className="table table-sm table-bordered">
                  <tbody>
                    <tr>
                      <td className="bg-light" width="40%"><strong>Has Outstanding Loan</strong></td>
                      <td>{property.hasLoan ? 'Yes' : 'No'}</td>
                    </tr>
                    {property.hasLoan && (
                      <>
                        <tr>
                          <td className="bg-light"><strong>Loan Amount</strong></td>
                          <td>{property.loanDetails?.originalAmount ? formatCurrency(property.loanDetails.originalAmount) : 'N/A'}</td>
                        </tr>
                        <tr>
                          <td className="bg-light"><strong>Outstanding Amount</strong></td>
                          <td>{property.loanDetails?.outstandingAmount ? formatCurrency(property.loanDetails.outstandingAmount) : 'N/A'}</td>
                        </tr>
                        <tr>
                          <td className="bg-light"><strong>Interest Rate</strong></td>
                          <td>{property.loanDetails?.interestRate ? `${property.loanDetails.interestRate}%` : 'N/A'}</td>
                        </tr>
                        <tr>
                          <td className="bg-light"><strong>Lender</strong></td>
                          <td>{property.loanDetails?.lender || 'N/A'}</td>
                        </tr>
                        <tr>
                          <td className="bg-light"><strong>Loan Start Date</strong></td>
                          <td>{property.loanDetails?.startDate ? formatDate(property.loanDetails.startDate) : 'N/A'}</td>
                        </tr>
                        <tr>
                          <td className="bg-light"><strong>Loan End Date</strong></td>
                          <td>{property.loanDetails?.endDate ? formatDate(property.loanDetails.endDate) : 'N/A'}</td>
                        </tr>
                      </>
                    )}
                  </tbody>
                </table>
              </div>
            </div>
          )}
          
          {(reportFormat === 'detailed' || reportFormat === 'verification') && (
            <div className="verification-section mb-4">
              <h5 className="border-bottom pb-2">Verification Status</h5>
              <div className="table-responsive">
                <table className="table table-sm table-bordered">
                  <tbody>
                    <tr>
                      <td className="bg-light" width="40%"><strong>DORIS Verified</strong></td>
                      <td><span className="badge bg-success">Yes</span></td>
                    </tr>
                    <tr>
                      <td className="bg-light"><strong>DLR Verified</strong></td>
                      <td><span className="badge bg-success">Yes</span></td>
                    </tr>
                    <tr>
                      <td className="bg-light"><strong>CERSAI Verified</strong></td>
                      <td><span className="badge bg-success">Yes</span></td>
                    </tr>
                    <tr>
                      <td className="bg-light"><strong>Last Verification Date</strong></td>
                      <td>{formatDate(new Date())}</td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
          )}
          
          {reportFormat === 'detailed' && (
            <div className="transaction-section mb-4">
              <h5 className="border-bottom pb-2">Transaction History</h5>
              <div className="table-responsive">
                <table className="table table-sm table-bordered">
                  <thead className="bg-light">
                    <tr>
                      <th>Date</th>
                      <th>Type</th>
                      <th>Parties Involved</th>
                      <th>Transaction Value</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <td>{formatDate(new Date(new Date().setFullYear(new Date().getFullYear() - 2)))}</td>
                      <td>Purchase</td>
                      <td>Previous Owner to {property.owner}</td>
                      <td>{formatCurrency(Math.round(property.marketValue * 0.8) || property.propertyDetails?.price * 0.8 || 0)}</td>
                    </tr>
                    {property.hasLoan && (
                      <tr>
                        <td>{property.loanDetails?.startDate ? formatDate(property.loanDetails.startDate) : formatDate(new Date(new Date().setFullYear(new Date().getFullYear() - 1)))}</td>
                        <td>Mortgage</td>
                        <td>{property.owner} with {property.loanDetails?.lender || 'Financial Institution'}</td>
                        <td>{property.loanDetails?.originalAmount ? formatCurrency(property.loanDetails.originalAmount) : 'N/A'}</td>
                      </tr>
                    )}
                  </tbody>
                </table>
              </div>
            </div>
          )}
          
          <div className="report-footer text-center mt-5 pt-3 border-top">
            <p className="small text-muted mb-0">This report is generated by ASSET-GURU for informational purposes only.</p>
            <p className="small text-muted mb-0">© ASSET-GURU. All rights reserved.</p>
          </div>
        </div>
      )}
    </div>
  );
}

export default PropertyReport; 